# Generated by Django 2.1.7 on 2020-02-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('ConfirmPassword', models.CharField(max_length=100)),
                ('Jwt', models.CharField(max_length=100)),
                ('CreateDateTime', models.DateTimeField()),
                ('LastUpdateDateTime', models.DateField()),
            ],
        ),
    ]
