# Generated by Django 2.1.7 on 2020-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='LastUpdateDateTime',
            field=models.DateTimeField(),
        ),
    ]
