# Generated by Django 2.1.7 on 2020-02-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0003_person_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ConfirmPassword',
        ),
    ]
