# Generated by Django 2.1.7 on 2020-02-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0004_remove_person_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CreateDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='LastUpdateDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
